### ISSUE TITLE
AuthorizationCodeReceived  call back is not firing from the Startup.Auth.cs file when openid connect response

### ISSUE THREAD

**Issue by BigBigg** [OfficeDev/Office-365-APIs-Starter-Project-for-ASPNETMVC#5]
I am trying to integrate office 365 into my existing mvc application.
For authentication into my application, i am trying to use OWIN middleware taking reference of this project but somehow AuthorizationCodeReceived call back is not firing from the Startup.Auth.cs file when openid connect response is received from Office 365 API.
Any idea, why AuthorizationCodeReceived call back is not firing?

**Comment by MIchaelMainer** [comment]
Closing due to no response.
