### ISSUE TITLE
not able get access token silently to get one drive files using Office365 OpenID access token

### ISSUE THREAD

**Issue by BigBigg** [OfficeDev/Office-365-APIs-Starter-Project-for-ASPNETMVC#6]
i am trying to get sharepoint\onedrive files using Office365 OpenID access token. i wrote below code to get access token silently (taking reference of  AuthenticationHelper.FileOperations.cs class from this sample project)
AuthenticationContext authContext = new AuthenticationContext(SettingsHelper.Authority, new NaiveSessionCache(signInUserId));
var authResult = await authContext.AcquireTokenSilentAsync(SettingsHelper.DiscoveryServiceResourceId,
                                                                                   new ClientCredential(SettingsHelper.ClientId,
                                                                                                        SettingsHelper.AppKey),
                                                                                   new UserIdentifier(userObjectId,
                                                                                                      UserIdentifierType.UniqueId))

when running through above statement i m getting exception "Failed to acquire token silently. Call method AcquireToken". 
I read on some of the articles that this is a known bug from microsoft. is it so?
or i m doing something silly which is causing this error.

**Comment by MIchaelMainer** [comment]
Since this may be related to issue 5, an we didn't get a response to issue 5, I'm closing this issue.
