### ISSUE TITLE
Signin fails

### ISSUE THREAD

**Issue by bdelaney** [OfficeDev/Office-365-APIs-Starter-Project-for-ASPNETMVC#7]
Followed all configuration steps. Project builds fine. I am guessing that my user profile (an MS, not Org account) in VS may be interfering as it does not match the client account for Office 365. Re-configuring connected services does not help. Error I see in Sign In page is below:

    Sorry, but we’re having trouble signing you in.
    We received a bad request.
    
    Additional technical information:
    Correlation ID: ae50f552-e7b4-4341-adce-465f17e35a21
    Timestamp: 2015-01-08 12:14:38Z
    AADSTS16000: Session is invalid due to recent password change.

Addendum: Closed and reopened project in VS. Returned to Connected Services dialog to try and change user. Now that is failing also. "Error Authenticating User"
Got past this. Hmm, had to authorize users in WAAD yet. Ok, done.
But same error when trying to Sign In after running (F5) with Chrome as browser.
Switching to IE, F5, is worse. Get a chance to login, but then stuck at a blank page.

**Comment by bdelaney** [comment]
tried a little debugging with Fiddler, Devtools, etc. There is a dependency on jquery-ui that is not being fulfilled. NuGet did not include that in the first Build. May fix that next.
But overall, the Sign In function seems to work correctly in Fiddler. It's just that I don't get anything but an empty page when the auth process is finished. Calling on other controllers in the URL (Calendar, Contacts) when the page is blank also creates a round-trip auth process. But again, ends on a blank page. No luck with debugging this one. Seeing some js errors, and also this one:

    A first chance exception of type 'Microsoft.IdentityModel.Protocols.OpenIdConnectProtocolException' occurred in     Microsoft.Owin.Security.OpenIdConnect.dll

**Comment by bdelaney** [comment]
Oh! Kick Me!
I came back to this after approaching it via the Windows App sample. I realized I had missed a crucial step in configuration, namely 'Users and Groups' permissions. Now I'm able to login and make use of O365 resources.

The other issue that stymied me is an old one. The fact that IIS Express, (still - even on CTP 4 of VS2013), will shut down unexpectedly when you are debugging a web app in IE.
But not in Chrome. Which is where I finally was able to run this sample app.

Sorry, cross this issue off unless it's valuable to someone else. I suppose that leaving out the permission to Users and Groups could trigger a warning in the Home/Index page (I see you have others there). Just saying that the Sign In error was not that helpful.

**Comment by MIchaelMainer** [comment]
Thank you for taking the time for sharing the fix with us. We've noted your suggestion about handling the exception caused by the missing User and Groups permissions. As you noted, a warning to check that permission would be very helpful.
