### ISSUE TITLE
Can we fetch all the files from within the root & sub folders?

### ISSUE THREAD

**Issue by BigBigg** [OfficeDev/Office-365-APIs-Starter-Project-for-ASPNETMVC#8]
Can we fetch all the files from within the root & sub folders using One drive API in a single call?

**Comment by MIchaelMainer** [comment]
You cannot get all of the files from the root and sub folders in a single call. Since this API only supports shallow folder traversal, you will have to make a request per folder. The maximum page size is 200 so for folders with more than 200 files and folders, you'll have to page the results.
